services:
  web:
    build: .
    volumes:
      - static:/app/staticfiles
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - MJML_HOST=mjml
      - MJML_PORT=28101
    depends_on:
      - db
      - mjml
    restart: always

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
      - static:/static:ro
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mjml:
    image: liminspace/mjml-tcpserver:1
    restart: always
    command: ["--mjml.validationLevel=strict"]

volumes:
   postgres_data:
   static:
   certbot_www:
   certbot_conf:
