services:
  web:
    build: .
    volumes:
      - ./static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - MJML_HOST=mjml
      - MJML_PORT=28101
    depends_on:
      - db
      - mjml

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - web

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mjml:
    image: liminspace/mjml-tcpserver:1
    restart: always
    ports:
      - "28101:28101"
    command: ["--mjml.validationLevel=strict"]

volumes:
   postgres_data:
