services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - MJML_HOST=mjml
      - MJML_PORT=28101
    depends_on:
      - db
      - mjml

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mjml:
    image: liminspace/mjml-tcpserver:1
    command: ["--mjml.validationLevel=strict"]

volumes:
   postgres_data:
