services:
  web:
    extends:
      file: docker-compose-base.yml
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

  db:
    extends:
      file: docker-compose-base.yml
      service: db
    ports:
      - "5431:5432"

  mjml:
    extends:
      file: docker-compose-base.yml
      service: mjml

  tailwind:
    volumes:
      - .:/project
    build:
      context: .
      dockerfile: tailwind-dockerfile
    stdin_open: true
    command: ["-i", "findshows/static/findshows/style.css", "-o", "findshows/static/findshows/tailwind.css"]

volumes:
   postgres_data:
