services:
  web:
    extends:
      file: docker-compose-base.yml
      service: web
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    restart: always

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - static:/static:ro
      - media:/media:ro
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw

  db:
    extends:
      file: docker-compose-base.yml
      service: db
    restart: always

  mjml:
    extends:
      file: docker-compose-base.yml
      service: mjml
    restart: always

volumes:
   postgres_data:
   static:
   media:
