# Generated by Django 5.0.7 on 2024-07-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('youtube_ids', models.JSONField()),
                ('socials_links', models.JSONField()),
                ('spotify_artist_id', models.CharField()),
                ('spotify_song_ids', models.JSONField()),
            ],
        ),
    ]
