# Generated by Django 5.0.7 on 2024-07-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Measuring Marigolds'),
            preserve_default=False,
        ),
    ]
