# Generated by Django 5.2 on 2025-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('BR', 'Warning/announcement banner'), ('AB', 'About page')], unique=True)),
            ],
        ),
    ]
