# Generated by Django 5.0.7 on 2024-08-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(default='https://www.dennys.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='findshows.artist'),
        ),
    ]
