# Generated by Django 5.0.7 on 2024-07-21 20:17

import findshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0002_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='spotify_artist_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify_song_ids',
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_platform',
            field=models.CharField(choices=[('SP', 'DSP'), ('BC', 'Bandcamp'), ('SC', 'Soundcloud'), ('NL', 'Not configured')], default='NL', max_length=2),
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_spotify_ids',
            field=models.JSONField(default=findshows.models.empty_list),
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_type',
            field=models.CharField(choices=[('AL', 'Album'), ('SO', 'Song'), ('NL', 'Not configured')], default='NL', max_length=2),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socials_links',
            field=models.JSONField(default=findshows.models.empty_list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_ids',
            field=models.JSONField(default=findshows.models.empty_list),
        ),
    ]
