# Generated by Django 5.0.7 on 2024-07-22 01:39

import findshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0003_remove_artist_spotify_artist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='listen_spotify_ids',
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_ids',
            field=models.JSONField(default=findshows.models.empty_list, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='listen_platform',
            field=models.CharField(choices=[('SP', 'DSP'), ('BC', 'Bandcamp'), ('SC', 'Soundcloud'), ('NL', 'Not configured')], default='NL', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='artist',
            name='listen_type',
            field=models.CharField(choices=[('AL', 'Album'), ('SO', 'Song'), ('NL', 'Not configured')], default='NL', editable=False, max_length=2),
        ),
    ]
