# Generated by Django 5.0.7 on 2024-07-30 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0004_remove_artist_listen_spotify_ids_artist_listen_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='local',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='similar_spotify_artists',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='listen_type',
            field=models.CharField(choices=[('AL', 'Album'), ('TR', 'Track'), ('NL', 'Not configured')], default='NL', editable=False, max_length=2),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('favorite_spotify_artists', models.JSONField()),
                ('followed_artists', models.ManyToManyField(related_name='followers', to='findshows.artist')),
                ('managed_artists', models.ManyToManyField(related_name='managing_users', to='findshows.artist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
