# Generated by Django 5.0.7 on 2024-09-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0004_alter_setorder_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorder',
            options={'ordering': ('order_number',)},
        ),
        migrations.AddField(
            model_name='concert',
            name='ticket_description',
            field=models.CharField(default='$10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='ages',
            field=models.CharField(blank=True, choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='setorder',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_order', to='findshows.artist'),
        ),
    ]
