# Generated by Django 5.2 on 2025-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0004_alter_artist_bio_alter_artist_listen_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='similar_musicbrainz_artists',
            field=models.ManyToManyField(help_text='Select 3 artists whose fans might also like to listen to this artist.', to='findshows.musicbrainzartist', verbose_name='Sounds like'),
        ),
    ]
