# Generated by Django 5.0.7 on 2024-07-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0005_artist_local_artist_similar_spotify_artists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
                ('ages', models.CharField(choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('ages', models.CharField(choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='temp_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='SetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.concert')),
            ],
            options={
                'unique_together': {('concert', 'order_number')},
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='artists',
            field=models.ManyToManyField(through='findshows.SetOrder', to='findshows.artist'),
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.venue'),
        ),
    ]
