# Generated by Django 5.2 on 2025-05-13 05:34

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0005_alter_artist_similar_musicbrainz_artists'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='musicbrainzartist',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['name'], name='mb_artist_gin_trgrm', opclasses=['gin_trgm_ops']),
        ),
    ]
