# Generated by Django 5.1.1 on 2024-11-04 01:35

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0006_concert_tags_userprofile_preferred_concert_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_concert_tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], max_length=8),
        ),
    ]
