# Generated by Django 5.0.7 on 2024-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0006_concert_venue_artist_temp_email_alter_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='youtube_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='listen_ids',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='similar_spotify_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socials_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_ids',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
