# Generated by Django 5.1.1 on 2024-11-04 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0007_concert_created_by_alter_concert_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile'),
            preserve_default=False,
        ),
    ]
