# Generated by Django 5.0.7 on 2024-07-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0007_artist_youtube_links_alter_artist_listen_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
