# Generated by Django 5.1.4 on 2025-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0008_concert_created_at_venue_created_at_venue_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBrainzArtist',
            fields=[
                ('mbid', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
    ]
