# Generated by Django 5.0.7 on 2024-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0008_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_spotify_artists',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_spotify_artist_ids',
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_spotify_artists_and_relateds',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
