# Generated by Django 5.0.7 on 2024-07-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0009_remove_userprofile_favorite_spotify_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_email',
            field=models.BooleanField(default=True),
        ),
    ]
