# Generated by Django 5.1.4 on 2025-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0009_musicbrainzartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='similar_spotify_artists',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='similar_spotify_artists_and_relateds',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_spotify_artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_spotify_artists_and_relateds',
        ),
        migrations.AddField(
            model_name='artist',
            name='similar_musicbrainz_artists',
            field=models.ManyToManyField(to='findshows.musicbrainzartist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_musicbrainz_artists',
            field=models.ManyToManyField(to='findshows.musicbrainzartist'),
        ),
    ]
