# Generated by Django 5.2.1 on 2025-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0009_alter_artist_profile_picture_alter_concert_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('generated_datetime', models.DateTimeField()),
                ('invite_code_hashed', models.CharField(editable=False, max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('invited_email',)},
            },
        ),
    ]
