# Generated by Django 5.1.4 on 2025-02-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0010_remove_artist_similar_spotify_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbrainzartist',
            name='similar_artists',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='musicbrainzartist',
            name='similar_artists_cache_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
