# Generated by Django 5.0.7 on 2024-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0010_userprofile_weekly_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_spotify_artist_ids',
        ),
        migrations.AddField(
            model_name='artist',
            name='similar_spotify_artists_and_relateds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_spotify_artists',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
