# Generated by Django 5.1.4 on 2025-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0011_musicbrainzartist_similar_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicbrainzartist',
            name='similar_artists',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
