# Generated by Django 5.2.3 on 2025-07-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0011_concert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(help_text='JPG of at most 2MB.', null=True, upload_to=''),
        ),
    ]
