# Generated by Django 5.0.7 on 2024-08-13 05:13

import datetime
import django.utils.timezone
import findshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0011_remove_userprofile_favorite_spotify_artist_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='time',
        ),
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 13)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='listen_links',
            field=models.TextField(blank=True, validators=[findshows.models.MultiURLValidator('LSN', 3)]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socials_links',
            field=models.JSONField(blank=True, default=list, validators=[findshows.models.LabeledURLsValidator()]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_links',
            field=models.TextField(blank=True, validators=[findshows.models.MultiURLValidator('YT', 2)]),
        ),
    ]
