# Generated by Django 5.2.6 on 2025-09-12 21:10

import findshows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0012_alter_artist_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=findshows.models.JPEGImageField(help_text='Uploaded file must be at most 30MB.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=findshows.models.JPEGImageField(help_text='Uploaded file must be at most 30MB. Vertical or square orientations display best.', upload_to=''),
        ),
    ]
