# Generated by Django 5.2.6 on 2025-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0013_alter_artist_profile_picture_alter_concert_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(help_text="Venues must have a public-facing\n    internet presence, even if it's just an Instagram page. This is for safety\n    reasons, as well as the means by which users will get venue addresses."),
        ),
    ]
