# Generated by Django 5.1.6 on 2025-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0013_alter_musicbrainzartist_similar_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicbrainzartist',
            name='similar_artists',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
