# Generated by Django 5.1.6 on 2025-03-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0014_alter_musicbrainzartist_similar_artists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='invited_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='invited_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_temp_artist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='requested_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ArtistLinkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('expiration_datetime', models.DateTimeField()),
                ('invite_code_hashed', models.CharField(max_length=128, unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
            ],
            options={
                'unique_together': {('invited_email', 'artist')},
            },
        ),
    ]
