# Generated by Django 5.1.6 on 2025-03-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0015_artist_invited_by_artist_invited_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_temp_artist',
            field=models.BooleanField(),
        ),
    ]
