# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0016_alter_artist_is_temp_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='temp_email',
        ),
    ]
