# Generated by Django 5.1.6 on 2025-03-13 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0017_remove_artist_temp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='invited_datetime',
        ),
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile'),
            preserve_default=False,
        ),
    ]
