# Generated by Django 5.1.6 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0020_artistlinkinginfo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='declined_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
