# Generated by Django 5.1.6 on 2025-03-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0020_userprofile_is_mod_alter_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='requested_datetime',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_active_request',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
