# Generated by Django 5.1.6 on 2025-03-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0021_venue_declined_listing_venue_is_verified'),
    ]

    operations = [
    ]
