# Generated by Django 5.1.6 on 2025-03-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0021_remove_artist_requested_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_active_request',
            field=models.BooleanField(default=False),
        ),
    ]
