# Generated by Django 5.1.6 on 2025-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0022_alter_artist_is_active_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistlinkinginfo',
            old_name='expiration_datetime',
            new_name='generated_datetime',
        ),
    ]
