# Generated by Django 5.1.6 on 2025-03-26 22:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0022_merge_20250326_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='given_artist_access_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gave_artist_access_to', to='findshows.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='given_artist_access_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 22, 43, 6, 633352, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistlinkinginfo',
            name='invite_code_hashed',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
