# Generated by Django 5.1.6 on 2025-03-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0023_userprofile_given_artist_access_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='given_artist_access_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
