# Generated by Django 5.1.6 on 2025-03-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0019_auto_20250316_1419'),
        ('findshows', '0023_rename_expiration_datetime_artistlinkinginfo_generated_datetime'),
        ('findshows', '0024_alter_userprofile_given_artist_access_datetime'),
    ]

    operations = [
    ]
