# Generated by Django 5.2 on 2025-04-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0025_merge_20250326_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='given_artist_access_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gave_artist_access_to', to='findshows.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='given_artist_access_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='managed_artists',
            field=models.ManyToManyField(blank=True, related_name='managing_users', to='findshows.artist'),
        ),
    ]
