services:
  web:
    build: ../app
    init: true
    env_file:
      - ../.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - MJML_HOST=mjml
      - MJML_PORT=28101
      - CACHE_LOCATION=memcached:11211
    depends_on:
      - db
      - mjml
      - memcached

  memcached:
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mjml:
    image: liminspace/mjml-tcpserver:1
    command: ["--mjml.validationLevel=strict"]

volumes:
   postgres_data:
