services:
  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        PIP_REQUIREMENTS: requirements/prod.txt
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    restart: always

  proxy:
    image: caddy:2.11
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ../config:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - static:/static:ro
      - media:/media:ro
    depends_on:
      - web
    restart: always

  db:
    extends:
      file: base.yml
      service: db
    restart: always

  mjml:
    extends:
      file: base.yml
      service: mjml
    restart: always

  memcached:
    extends:
      file: base.yml
      service: memcached
    restart: always

volumes:
   postgres_data:
   static:
   media:
   caddy_data:
   caddy_config:
