#####################
# 1: Base build stage
ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}-slim AS builder

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set up a venv for more predictable copying to production stage
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip
RUN pip install --upgrade pip

# Install Python dependencies
ARG PIP_REQUIREMENTS
COPY requirements/ ./requirements/
RUN pip install -r $PIP_REQUIREMENTS

####################
# 2: Production stage

FROM python:${PYTHON_VERSION}-slim

RUN useradd -m -r appuser && \
   mkdir /app && \
   chown -R appuser /app

# Copy the Python dependencies from the builder stage
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Set the working directory
WORKDIR /app

# Copy application code
COPY --chown=appuser:appuser . .

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Switch to non-root user
USER appuser

# Expose the application port
EXPOSE 8000

RUN chmod +x /app/entrypoint.prod.sh
CMD ["/app/entrypoint.prod.sh"]
