# Generated by Django 5.2 on 2025-04-24 21:13

import django.db.models.deletion
import findshows.models
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('doors_time', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('ages', models.CharField(blank=True, choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2)),
                ('ticket_link', models.URLField(blank=True)),
                ('ticket_description', models.CharField()),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicBrainzArtist',
            fields=[
                ('mbid', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('similar_artists', models.JSONField(editable=False, null=True)),
                ('similar_artists_cache_datetime', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('bio', models.TextField(blank=True)),
                ('local', models.BooleanField()),
                ('is_active_request', models.BooleanField(default=False)),
                ('is_temp_artist', models.BooleanField()),
                ('listen_links', models.TextField(blank=True, validators=[findshows.models.MultiURLValidator('LSN', 3)])),
                ('listen_platform', models.CharField(choices=[('SP', 'DSP'), ('BC', 'Bandcamp'), ('SC', 'Soundcloud'), ('NL', 'Not configured')], default='NL', editable=False, max_length=2)),
                ('listen_type', models.CharField(choices=[('AL', 'Album'), ('TR', 'Track'), ('NL', 'Not configured')], default='NL', editable=False, max_length=2)),
                ('listen_ids', models.JSONField(default=list, editable=False)),
                ('youtube_links', models.TextField(blank=True, validators=[findshows.models.MultiURLValidator('YT', 2)])),
                ('youtube_ids', models.JSONField(blank=True, default=list, editable=False)),
                ('socials_links', models.JSONField(blank=True, default=list, validators=[findshows.models.LabeledURLsValidator()])),
                ('similar_musicbrainz_artists', models.ManyToManyField(to='findshows.musicbrainzartist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_order', to='findshows.artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.concert')),
            ],
            options={
                'ordering': ('order_number',),
                'unique_together': {('concert', 'order_number')},
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='artists',
            field=models.ManyToManyField(through='findshows.SetOrder', to='findshows.artist'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_concert_tags', multiselectfield.db.fields.MultiSelectField(choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], max_length=8)),
                ('weekly_email', models.BooleanField(default=True)),
                ('given_artist_access_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_mod', models.BooleanField(default=False)),
                ('favorite_musicbrainz_artists', models.ManyToManyField(blank=True, to='findshows.musicbrainzartist')),
                ('followed_artists', models.ManyToManyField(blank=True, related_name='followers', to='findshows.artist')),
                ('given_artist_access_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gave_artist_access_to', to='findshows.userprofile')),
                ('managed_artists', models.ManyToManyField(blank=True, related_name='managing_users', to='findshows.artist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile'),
        ),
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(unique=True)),
                ('address', models.CharField()),
                ('ages', models.CharField(choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2)),
                ('website', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('declined_listing', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.venue'),
        ),
        migrations.CreateModel(
            name='ArtistLinkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('generated_datetime', models.DateTimeField()),
                ('invite_code_hashed', models.CharField(editable=False, max_length=128, unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('invited_email', 'artist')},
            },
        ),
    ]
