# Generated by Django 5.2.7 on 2026-03-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='listen_ids',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='listen_links',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='listen_platform',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='listen_type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='youtube_ids',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='youtube_links',
        ),
        migrations.AlterField(
            model_name='artist',
            name='similar_musicbrainz_artists',
            field=models.ManyToManyField(help_text="Select 3 artists whose fans might also like to listen to this artist. If an artist doesn't appear on the list, it means MusicBrainz doesn't have any similarity data on them; please pick another while their database grows!", to='findshows.musicbrainzartist', verbose_name='Sounds like'),
        ),
        migrations.CreateModel(
            name='ListenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.URLField()),
                ('iframe_url', models.URLField(editable=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.URLField()),
                ('iframe_url', models.URLField(editable=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
