# Generated by Django 6.0.3 on 2026-04-13 01:27

from django.db import migrations, models

from findshows.models import ArtistVerificationStatus


def set_artist_verification_status(apps, schema_editor):
    UserProfile = apps.get_model("findshows", "UserProfile")
    for profile in UserProfile.objects.all():
        if not profile.given_artist_access_by:
            continue
        if profile.given_artist_access_by.user.is_mod or profile.given_artist_access_by.user.is_staff:
            profile.artist_verification_status = ArtistVerificationStatus.VERIFIED
        else:
            profile.artist_verification_status = ArtistVerificationStatus.INVITED
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0002_remove_artist_listen_ids_remove_artist_listen_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_active_request',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist_verification_status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('VE', 'Verified'), ('IN', 'Invited'), ('DE', 'Deverified'), ('NL', 'Not local')], max_length=2, null=True),
        ),
        migrations.RunPython(set_artist_verification_status)
    ]
