# Generated by Django 6.0.4 on 2026-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0003_remove_artist_is_active_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='socials_links',
            field=models.JSONField(blank=True, default=list, help_text='Enter links to socials, website, email, etc. Include protocol (https://, http://, or mailto:)'),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='type',
            field=models.CharField(choices=[('BR', 'Announcement banner'), ('AB', 'About page'), ('ES', 'Subject for weekly recommendation email'), ('EH', 'Header message for weekly recommendation email'), ('AI', 'Artist invite email'), ('TS', 'Terms of service')], max_length=2, unique=True),
        ),
    ]
