# Generated by Django 6.0.4 on 2026-04-22 21:31

from django.conf import settings
from django.db import migrations
from django.urls import reverse

from findshows.models import CustomTextTypes

PROTOCOL = "http" if settings.IS_DEV else "https"
def local_url_to_email(local_url, display=""):
    if display:
        return f"[{display}]({PROTOCOL}://{settings.HOST_NAME}{local_url})"
    else:
        return f"{PROTOCOL}://{settings.HOST_NAME}{local_url}"


def create_default_custom_texts(apps, schema_editor):
    CustomText = apps.get_model("findshows", "CustomText")

    default_texts = {
        CustomTextTypes.ABOUT: "Ask your local mods to fill out this page and tell you who they are! Or read below for information on the software running this site.",
        CustomTextTypes.WEEKLY_EMAIL_SUBJECT: "Your weekly local music recs",
        CustomTextTypes.WEEKLY_EMAIL_HEADER: "Thanks for subscribing to the email list and supporting local music!",
        CustomTextTypes.ARTIST_INVITE_EMAIL: f"""
**{settings.SITE_TITLE}** is an online, media-rich bulletin board for our
local music scene.

**Features for listeners**

- A single weekly email: all the shows from bands you follow, a few from bands you don't!
- Shows searchable anytime on the site.
- Embedded audio players for easy show browsing.

**Features for artists**

- Every show goes into every follower's inbox, and is recommended to some other users.
- Profile doubles as a simple EPK for booking.
- Profile information populates automatically to concert listings.
- One-click follow link (for social media etc) and QR code (for your merch table).
- Future features: release announcements, artist discovery search, RSS, and more!

Check out the {local_url_to_email(reverse("findshows:artist_faq"), "Artist FAQ")} for more details.

Instagram and other big social media are filling our feeds with irrelevant content and otherwise
[enshittifying](https://en.wikipedia.org/wiki/Enshittification) the internet.
This site aims to be more of what we want and less of what we don't. More irl
connection, more relevant information; less distraction, less stimulation, less
scrolling.

All offered in the DIY ethos; libre/open source forever and as gratis as we can sustainably make it.
        """,
    }

    for type in CustomTextTypes.values:
        default_text = default_texts[type] if type in default_texts else ""
        custom_texts = CustomText.objects.filter(type=type)
        if len(custom_texts) > 0:
            for ct in custom_texts[1:]:
                ct.delete()
            custom_text = custom_texts[0]
            if custom_text.text:
                continue
        else:
            custom_text = CustomText(type=type)
        custom_text.text = default_text
        custom_text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0004_alter_artist_socials_links_alter_customtext_text_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_custom_texts, reverse_code=migrations.RunPython.noop),
    ]
