# Generated by Django 6.0.4 on 2026-04-22 21:31

from django.conf import settings
from django.db import migrations
from django.urls import reverse

from findshows.models import CustomTextTypes

PROTOCOL = "http" if settings.IS_DEV else "https"
def local_url_to_email(local_url, display=""):
    if display:
        return f"[{display}]({PROTOCOL}://{settings.HOST_NAME}{local_url})"
    else:
        return f"{PROTOCOL}://{settings.HOST_NAME}{local_url}"


def create_default_custom_texts(apps, schema_editor):
    CustomText = apps.get_model("findshows", "CustomText")

    default_texts = {
        CustomTextTypes.ABOUT: "Ask your local mods to fill out this page and tell you who they are! Or read below for information on the software running this site.",
        CustomTextTypes.WEEKLY_EMAIL_SUBJECT: "Your weekly local music recs",
        CustomTextTypes.WEEKLY_EMAIL_HEADER: "Thanks for subscribing to the email list and supporting local music!",
        CustomTextTypes.ARTIST_INVITE_EMAIL: f"""
**For more information, read on!**

Or ask the person who invited you, or
{local_url_to_email(reverse("findshows:contact"), "contact us")}.

**{settings.SITE_TITLE}** is an online bulletin board for keeping up with our
local music scene. Artists post shows, and anybody can sign up for a weekly
roundup email with shows recommended through one or more of:

- Followed artists: any shows with a band you follow on the bill will go
  right to the top of your weekly email.
- Similar artists: thanks to open-source data from ListenBrainz.org, you can enter
  artists you listen to and get a rough recommendation for similar local artists.
- Random: if you don't want _any_ algorithm in your life, you can choose
  to just get a few random shows instead (along with your followed artists)

Visit the site anytime to browse shows on a given date. Preview what kind of
show you're in for with an embedded player for each artist right in the search
results.

**Make a profile to**:

- Set your preview tracks, similar artists, and other info that will be
  automatically transferred onto any show listings you're on the bill for.
- Post your shows
- Get a link/QR code for your merch table to make it easy for folks to follow
  you on the site.
- Invite your artist friends to join so you can follow them and never miss a show again!
- Use it as a super-simple EPK for booking (image, bio, stream-able recordings on one page).
- (in the near future, we're planning the ability to announce releases as well.)

That's really it! Instagram and other social media aren't showing your posts to
people who follow you anymore, instead filling our feeds with algorithmically
selected content that we never asked for. This site aims to be more of what we
want and less of what we don't. More irl connection, more of the information
we're looking for, more old-fashioned emails (or RSS!); less distraction, less
stimulation, less enshittification, less scrolling.

All offered in the spirit & ethos of DIY, libre/open source forever and as
gratis as we can sustainably make it.
        """,
    }

    for type in CustomTextTypes.values:
        default_text = default_texts[type] if type in default_texts else ""
        custom_texts = CustomText.objects.filter(type=type)
        if len(custom_texts) > 0:
            for ct in custom_texts[1:]:
                ct.delete()
            custom_text = custom_texts[0]
            if custom_text.text:
                continue
        else:
            custom_text = CustomText(type=type)
        custom_text.text = default_text
        custom_text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0004_alter_artist_socials_links_alter_customtext_text_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_custom_texts, reverse_code=migrations.RunPython.noop),
    ]
