# Generated by Django 6.0.4 on 2026-05-08 21:04

import findshows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0005_data_set_default_custom_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_picture_small',
            field=findshows.models.JPEGImageField(default='', max_dimension=400, max_filesize_kb=100, upload_to=findshows.models.prof_pic_name_small),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='poster_small',
            field=findshows.models.JPEGImageField(default='', editable=False, max_dimension=400, max_filesize_kb=100, upload_to=findshows.models.poster_name_small),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=findshows.models.JPEGImageField(help_text='Uploaded file must be at most 30MB.', null=True, upload_to=findshows.models.prof_pic_name),
        ),
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=findshows.models.JPEGImageField(help_text='Uploaded file must be at most 30MB. Vertical or square orientations display best.', upload_to=findshows.models.poster_name),
        ),
    ]
