# Generated by Django 6.0.4 on 2026-05-08 04:59

from django.db import migrations

from findshows import models


def downscale_images(apps, schema_editor):
    Concert = apps.get_model("findshows", "Concert")
    for concert in Concert.objects.all():
        if not concert.poster:
            continue
        with concert.poster.open() as content:
            concert.poster.save(models.poster_name(concert, ""), content)
            concert.poster_small.save(models.poster_name_small(concert, ""), content)

    Artist = apps.get_model("findshows", "Artist")
    for artist in Artist.objects.all():
        if not artist.profile_picture:
            continue
        with artist.profile_picture.open() as content:
            artist.profile_picture.save(models.prof_pic_name(artist, ""), content)
            artist.profile_picture_small.save(models.prof_pic_name_small(artist, ""), content)


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0006_artist_profile_picture_small_concert_poster_small_and_more'),
    ]

    operations = [
        migrations.RunPython(downscale_images, reverse_code=migrations.RunPython.noop),
    ]
