# Generated by Django 5.2 on 2025-05-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0006_musicbrainzartist_mb_artist_gin_trgrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbrainzartist',
            name='disambiguation',
            field=models.CharField(null=True),
        ),
    ]
