# Generated by Django 6.0.4 on 2026-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0007_data_generate_small_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('type', models.CharField(choices=[('hlp', 'Tech support/help'), ('mod', 'Moderator question'), ('ftr', 'Feature request'), ('bug', 'Bug report'), ('oth', 'Other')], max_length=3)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(help_text='Please include as much detail as possible for the quickest help.', max_length=2000)),
            ],
        ),
    ]
