# Generated by Django 5.2.1 on 2025-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0007_musicbrainzartist_disambiguation'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='cancelled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
