# Generated by Django 5.2.1 on 2025-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0008_concert_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(help_text='JPG of at most 2MB.  Profile pictures will be cropped to a circle.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=models.ImageField(help_text='JPG of at most 2MB. Vertical or square orientations display best.', upload_to=''),
        ),
    ]
