# Generated by Django 6.0.4 on 2026-05-14 16:56

from django.db import migrations, models

from findshows.models import CustomTextTypes


def create_donation_text(apps, schema_editor):
    CustomText = apps.get_model("findshows", "CustomText")
    custom_texts = CustomText.objects.filter(type="DN")
    if len(custom_texts) > 0:
        if custom_texts[0].text:
            return
        else:
            for custom_text in custom_texts:
                custom_text.delete()
    custom_text = CustomText(type="DN",
                             text="## Help with hosting costs\n\nThis site costs money to host! Please consider helping out with a one-time or monthly donation.\n\n(This site has not set up a donation link yet)")
    custom_text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtext',
            name='type',
            field=models.CharField(choices=[('BR', 'Announcement banner'), ('AB', 'About page'), ('ES', 'Subject for weekly recommendation email'), ('EH', 'Header message for weekly recommendation email'), ('AI', 'Artist invite email'), ('TS', 'Terms of service'), ('DN', 'Donation texts')], max_length=2, unique=True),
        ),

        migrations.RunPython(create_donation_text, reverse_code=migrations.RunPython.noop),
    ]
