# Generated by Django 6.0.4 on 2026-05-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0009_alter_customtext_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='qr_kit',
            field=models.FileField(editable=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='concert',
            name='announced',
            field=models.DateField(editable=False, null=True),
        ),
    ]
