# Generated by Django 6.0.4 on 2026-05-25 21:58

from django.core.files.base import ContentFile
from django.db import migrations
from findshows import pdfgen

def generate_qr_kits(apps, schema_editor):
    Artist = apps.get_model('findshows', 'Artist')
    artists = Artist.objects.all()
    for artist in artists:
        if not (artist.pk and artist.name):
            return
        artist.qr_kit = ContentFile(pdfgen.generate_artist_qr_kit(artist.pk, artist.name),
                                  f"{artist.name}_qr_kit.pdf")
        artist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0010_artist_qr_kit_concert_announced'),
    ]

    operations = [
        migrations.RunPython(generate_qr_kits, reverse_code=migrations.RunPython.noop),
    ]
