# Generated by Django 6.0.4 on 2026-07-07 06:01

import django.db.models.deletion
import findshows.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0011_data_generate_qr_kits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='local',
            field=models.BooleanField(help_text='Local artists can post shows.'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='similar_musicbrainz_artists',
            field=models.ManyToManyField(help_text='Select 3 well-known artists whose fans might like your music.', to='findshows.musicbrainzartist', verbose_name='Sounds like'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socials_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='concert',
            name='ages',
            field=models.CharField(blank=True, choices=[('AA', 'All ages'), ('17', '17+'), ('18', '18+'), ('21', '21+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.CharField(blank=True, help_text='50 characters of vibes.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], help_text='\n    Select what best represents the show as a whole.', max_length=15),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(help_text='Select\n    a venue from the database, or create one if needed.', on_delete=django.db.models.deletion.CASCADE, to='findshows.venue'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_musicbrainz_artists',
            field=models.ManyToManyField(blank=True, help_text="For the bands you don't follow, you can get personalized\n        recommendations by filling this out. Leave blank for random recs.", to='findshows.musicbrainzartist', verbose_name='Favorite artists'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_concert_tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('OG', 'Original music'), ('CV', 'Cover set'), ('DJ', 'DJ set')], help_text='Optional filter tags for your\n                                             weekly email.', max_length=15, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_email',
            field=models.BooleanField(default=True, help_text="All the shows from bands you follow, then a few from bands you don't."),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.CharField(help_text='Concerts link here. Should include public address or a contact method to get the address.', validators=[findshows.models.EmailOrURLValidator()], verbose_name='Venue Website'),
        ),
    ]
