# Generated by Django 6.0.4 on 2026-08-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0013_concert_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInviteLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('generated_datetime', models.DateTimeField()),
                ('code_hashed', models.CharField(editable=False, max_length=128, unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistManagementLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('generated_datetime', models.DateTimeField()),
                ('code_hashed', models.CharField(editable=False, max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.userprofile')),
            ],
            options={
                'unique_together': {('email', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_datetime', models.DateTimeField()),
                ('code_hashed', models.CharField(editable=False, max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='artistlinkinginfo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='artistlinkinginfo',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistlinkinginfo',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findshows.venue'),
        ),
        migrations.DeleteModel(
            name='ArtistLinkingInfo',
        ),
    ]
