# Generated by Django 6.0.4 on 2026-08-18 20:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshows', '0014_artistinvitelinkcode_artistmanagementlinkcode_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['name'], name='artist_gin_trgrm', opclasses=['gin_trgm_ops']),
        ),
    ]
